spring.application.name=jobtracker
spring.datasource.url=spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=uaFaFAXUCUkhHaSYadTGGdSEcoMCBLTJ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9090